### PR TITLE
Story part3

### PR DESCRIPTION
**Pull request by dwds**
This is just an outline so far, but I'm going ahead with the Pull Request to get the conversation started. I went dark and weird, as promised.

### CODE REVIEW

**Comment by dwds** [comment]
Don't read before bed. 2spoopy

**Comment by dwds** [comment]
Also, I had the idea to use 'you' instead of 'Vincent' throughout the story. Let me know what you think.

**Comment by KyWalker** [comment]
What did I just read? I love it! I was horrified, but laughed out loud at the same time!
And I like the idea of using 'you' instead of Vincent, I think it will make the story feel more immersive.

**Comment by dwds** [comment]
Hello, everyone. I've _fleshed_ out the story (pun INTENDED). Please check it out and leave some comments so we can get this baby merged!

**Comment by KyWalker** [comment]
I really great ending to our story. How ever @chall05 designs the puzzle cube I might try to incorporate it into the design theme for the part 3 page. I'm thinking blacks, greys, and glowing dark greens. Weird little symbols and runes. But I'll have to wait and see what Callan decides.

**Pull request merged**
