### PR TITLE
Stylethree

### PR DESCRIPTION
**Pull request by KyWalker**
The style sheet for part three, plus some images and font files.

### CODE REVIEW

**Comment by dwds** [comment]
This looks great! I love the arcane symbols. Is @bkeeran1 filling in the placeholder images?

**Comment by KyWalker** [comment]
Thanks, and that was the plan.

**Comment by dwds** [comment]
Do we want to have a nav bar?

**Comment by millarmadison** [comment]
I think it looks awesome! good job Kylie!

**Comment by vhoge94** [comment]
Wow! What is that background, and the text fonts are great.

**Comment by KyWalker** [comment]
Okay, the navigation bar is officially gone!

**Comment by luka-zelenovic** [comment]
I like it, just waiting on the images.

**Pull request merged**
