### PR TITLE
i added the second part of the story to the branch!

### PR DESCRIPTION
**Pull request by millarmadison**
Hi everyone,
Here is part two of our story. Please comment and let me know what you think!

### CODE REVIEW

**Comment by KyWalker** [comment]
Its a little on the short side. There is only one more story part after this one and it wouldn't make a lot of sense for every major event in the story to happen in the last section. There is no suspenseful build up.

**Comment by luka-zelenovic** [comment]
Add classes to each paragraph like Jaylen did.

**Comment by Jax-Tsukuyomu** [comment]
There should be a lead up to the next puzzle as well. I recommend collaberating with whomever is making the next puzzle. That way the story can have a good stopping point. It's missing a point. The story needs an advancement.

**Comment by dwds** [comment]
Nice changes, @millarmadison. Will you just add some line breaks, so we don't have to horizontally scroll to read the whole paragraph?

**Pull request merged**
