### PR TITLE
Add limitations ideas to ideas.txt

### PR DESCRIPTION
**Pull request by dwds**
Please review the ideas for limitations and discuss.

### CODE REVIEW

**Comment by millarmadison** [comment]
hey!!!!!!!!!

**Comment by Jax-Tsukuyomu** [comment]
I am all for it! What if we had an actual breakdown of the work? Like physically?

**Comment by Jax-Tsukuyomu** [comment]
Ahhhh!

**Comment by millarmadison** [comment]
I've gathered you all here today for an important meeting. We have a big project to do and I'm the captain.

**Comment by BMGaither** [comment]
I am for the idea

**Comment by millarmadison** [comment]
I'm for the idea as well, great suggestion Jaylen!

**Comment by vhoge94** [comment]
what different teams are needed to complete this project? Writer, designers, programmers

**Comment by Jax-Tsukuyomu** [comment]
Ahhh! Good point Verne!

**Comment by KyWalker** [comment]
Jalen what do you mean by breaking down the work "Physically"?

**Comment by dwds** [comment]
@Jax-Tsukuyomu What do you mean physically?

**Comment by vhoge94** [comment]
who is on what team

**Comment by Jax-Tsukuyomu** [comment]
Well KyWalker, I envisioned it to be more of a breakdown of teams as stated before. And then People have a specific slot where their skills could be utilized. But have it on physical paper.

**Comment by jf-42** [comment]
Why not digital paper?

**Comment by bkeearan1** [comment]
the problem I have with that workflow is the idea that its a "factory line" and we wont all be working together, it'll be one group at a time, i'd like to keep away from that.

**Comment by vhoge94** [comment]
So Brody and Jalen are our writers

**Comment by millarmadison** [comment]
I agree with @bkeeraran1. I thrive in team environments!

**Comment by luka-zelenovic** [comment]
I guess I'll do the programming part.

**Comment by jf-42** [comment]
Then how do we gknow what everyone will be doing?

**Comment by vhoge94** [comment]
Who is designing

**Comment by Jax-Tsukuyomu** [comment]
Get 'Em! I'm fine with writing. I'd also like to have a hand in different aspect as well.

**Comment by BMGaither** [comment]
I'm with programming as well

**Comment by dwds** [comment]
@bkeearan1 I don't think that's necessarily true. But even if it was, is there anything wrong with that as a form of creative expression? See Surrealism, especially https://en.wikipedia.org/wiki/Exquisite_corpse

**Comment by vhoge94** [comment]
I am good with doing anything

**Comment by jf-42** [comment]
image

**Comment by KyWalker** [comment]
Can I make the suggestion that we plan this project out thoroughly before we start. I like organization.

**Comment by bkeearan1** [comment]
round table ideas? we could all be working on our respected sides at the same time? also im down for set design, my art style is mainly perspective.

**Comment by Jax-Tsukuyomu** [comment]
I know you do, @KyWalker.

**Pull request merged**
